#!/usr/bin/env python3
"""
generate_chapters.py — 批次生成 Python 學堂所有章節
從結構化 outline 一次生成 60 個 .md 檔
每個檔保留 lesson-header 結構 + 真實可跑的 code + 練習題
"""
import os
from pathlib import Path

ROOT = Path("/Users/elvis/projects/python-learning-site/docs")

# 統一 lesson header 模板
def lesson_header(chapter_tag, h1, time, audience, level="入門"):
    return f"""---
title: "{h1}"
---

<div class="lesson-header">
  <span class="chapter-tag">{chapter_tag}</span>
  <h1>{h1}</h1>
  <div class="meta">
    <span>⏱️ {time}</span>
    <span>📖 {audience}</span>
    <span>🎯 {level}</span>
  </div>
</div>

"""


# ===========================================================
# 第 0 章 — 環境準備 (剩 0.3, 0.4, 0.5, quiz)
# ===========================================================
CHAPTER_0 = [
    ("0.3 VS Code 設定", "VS Code 設定", "10 分鐘", "🛠️ 必做", "VS Code 安裝 + Python 擴充 + 第一支程式", [
        "## 🎯 學習目標",
        "- 安裝 VS Code 並設定為 Python 編輯器",
        "- 安裝 Python 與 Jupyter 兩個必備擴充",
        "- 學會用 VS Code 跑 .py 檔和 .ipynb notebook",
        "- 認識 settings.json 怎麼改",
        "",
        "## ⬇️ 安裝 VS Code",
        "1. 開瀏覽器到 [https://code.visualstudio.com/](https://code.visualstudio.com/)",
        "2. 下載安裝檔並執行",
        "3. macOS: 拖到 Applications",
        "4. Windows: 一直下一步",
        "5. Linux: 用 `snap` 或 `apt` 安裝",
        "",
        "## 🔌 安裝必備擴充",
        "打開 VS Code，按 `Cmd+Shift+X`（macOS）或 `Ctrl+Shift+X`（Windows）打開擴充市集，搜尋並安裝：",
        "",
        "| 擴充 ID | 用途 |",
        "|---|---|",
        "| `ms-python.python` | Python 語言支援（必裝） |",
        "| `ms-toolsai.jupyter` | Jupyter notebook 支援 |",
        "| `ms-python.vscode-pylance` | Python 智慧提示 |",
        "| `njpwerner.autodocstring` | 自動 docstring |",
        "",
        "## ⚙️ 設定 Python interpreter",
        "1. 按 `Cmd+Shift+P` 打開命令選擇",
        "2. 輸入 \"Python: Select Interpreter\"",
        "3. 選擇你剛安裝的 Python 3.11+",
        "",
        "## ✏️ 第一支 .py 檔",
        "1. 新增檔案 `hello.py`",
        "2. 輸入：",
        "```python",
        "name = input('你叫什麼名字？ ')",
        "print(f'哈囉 {name}！歡迎來到 Python 學堂！')",
        "```",
        "3. 按右上 ▶︎ 執行（或 `Ctrl+F5`）",
        "4. 終端機會問你名字，輸入後看到歡迎訊息",
        "",
        "## 📓 Jupyter notebook 模式",
        "1. 安裝 Jupyter 擴充後，`.ipynb` 檔案可以直接開",
        "2. 按 `+ Code` 加 cell",
        "3. 輸入 `print('Hello')`",
        "4. 按 `Shift+Enter` 執行",
        "",
        "## 🎨 推薦設定（settings.json）",
        "```json",
        "{",
        '  "editor.fontSize": 14,',
        '  "editor.fontFamily": "JetBrains Mono, monospace",',
        '  "editor.minimap.enabled": false,',
        '  "editor.formatOnSave": true,',
        '  "python.defaultInterpreterPath": "python3"',
        "}",
        "```",
        "",
        "## ❗ 常見錯誤",
        "1. **VS Code 找不到 Python** → 重選 interpreter",
        "2. **擴充裝了沒反應** → 重啟 VS Code",
        "3. **中文輸入亂碼** → 終端機設定 UTF-8",
        "",
        "## 📚 延伸閱讀",
        "- [VS Code Python 教學](https://code.visualstudio.com/docs/python/python-tutorial)",
        "- [Jupyter in VS Code](https://code.visualstudio.com/docs/datascience/jupyter-notebooks)",
        "",
        "---",
        "",
        "下一課：[0.4 Hello, Python!](04-hello.md) — 寫你人生第一支程式 ✨",
    ]),

    ("0.4 Hello, Python!", "Hello, Python!", "5 分鐘", "🚀 必做", "寫第一行程式", [
        "## 🎯 學習目標",
        "- 用 3 種方式執行你的第一個 Python 程式",
        "- 學會 `print()` 和 `input()`",
        "- 寫一支小程式跟自己打招呼",
        "",
        "## 💻 方式 1：直接打 `python3`",
        "在終端機打 `python3`，進入 REPL 模式：",
        "```python",
        ">>> print('Hello, World!')",
        "Hello, World!",
        "```",
        "",
        "## 📝 方式 2：寫 .py 檔",
        "新增 `hello.py`：",
        "```python",
        "# 我的第一支 Python 程式",
        "name = input('你叫什麼名字？ ')",
        "print(f'哈囉 {name}！歡迎來到 Python 學堂！ 🐍')",
        "```",
        "在終端機跑：`python3 hello.py`",
        "",
        "## 📓 方式 3：Jupyter notebook",
        "新增 cell：",
        "```python",
        "name = 'Elvis'",
        "print(f'哈囉 {name}！')",
        "```",
        "按 `Shift+Enter`",
        "",
        "## 🎯 練習：寫自我介紹",
        "用 `input()` 問使用者：",
        "- 名字",
        "- 年齡",
        "- 興趣",
        "然後用 `f-string` 印出一段自我介紹",
        "",
        "範例：",
        "```python",
        "name = input('你叫什麼名字？ ')",
        "age = input('你幾歲？ ')",
        "hobby = input('你的興趣是？ ')",
        "print(f'=== 自我介紹 ===')",
        "print(f'你好，我是 {name}')",
        "print(f'{age} 歲')",
        "print(f'興趣是 {hobby}')",
        "print(f'很高興認識你！')",
        "```",
        "",
        "## ❗ 常見錯誤",
        "1. `input()` 拿到的都是字串，要 `int(input())` 轉數字",
        "2. `print(f'...')` 前面一定要小寫 f（format string）",
        "3. 單引號跟雙引號要對稱",
        "",
        "## 📚 延伸閱讀",
        "- [print() 文件](https://docs.python.org/3/library/functions.html#print)",
        "- [input() 文件](https://docs.python.org/3/library/functions.html#input)",
        "",
        "---",
        "",
        "下一課：[0.5 怎麼問問題 + Debug](05-how-to-ask.md) — 工程師最重要的技能 🔍",
    ]),

    ("0.5 怎麼問問題 + Debug", "怎麼問問題 + Debug", "5 分鐘", "🔍 必讀", "工程師最重要的 skill", [
        "## 🎯 學習目標",
        "- 學會**看懂錯誤訊息**",
        "- 知道**怎麼搜尋**錯誤",
        "- 學會**怎麼問問題**（MCVE 原則）",
        "- 學會用 `print()` debug",
        "",
        "## 🔍 看懂錯誤訊息",
        "Python 錯誤訊息有 3 個關鍵：",
        "```",
        "Traceback (most recent call last):",
        "  File 'hello.py', line 3    ← 第幾行",
        "    print(name)",
        "NameError: name 'name' is not defined    ← 什麼錯",
        "```",
        "記住：**Traceback 最後一行才是錯誤類型**，上面的行號是「在哪裡發生」。",
        "",
        "## 🔎 怎麼搜尋錯誤",
        "1. **複製錯誤訊息最後一行**",
        "2. **Google 搜尋**：`python NameError: name is not defined`",
        "3. **前三個結果**通常有解答（Stack Overflow 為主）",
        "",
        "## 📝 怎麼問問題（MCVE 原則）",
        "**M**inimal **C**omplete **V**erifiable **E**xample — 最小可重現範例",
        "",
        "好的問題：",
        "```python",
        "# 我想問：為什麼這個會錯？",
        "x = 5",
        "y = 0",
        "print(x / y)  # 預期輸出 5，實際跳 ZeroDivisionError",
        "```",
        "",
        "不好的問題：",
        "> 「我的程式壞了，怎麼辦？」 ← 沒人幫得了你",
        "",
        "## 🦆 橡皮鴨法",
        "把你的程式**一行一行唸給橡皮鴨聽**（或任何不會動的東西）。",
        "當你試著解釋時，**自己就會發現 bug 在哪**。",
        "",
        "這是工程師最常用的除錯技巧，聽起來很蠢但超有效。",
        "",
        "## 🐛 print() Debug 大法",
        "```python",
        "def calculate(x, y):",
        "    print(f'DEBUG: x={x}, y={y}')    # 追蹤變數",
        "    result = x * y",
        "    print(f'DEBUG: result={result}')",
        "    return result",
        "",
        "answer = calculate(3, 4)",
        "```",
        "在每個關鍵點 print，**找出哪裡不如預期**。",
        "",
        "## ❗ 常見錯誤類型速查",
        "| 錯誤 | 原因 | 修正 |",
        "|---|---|---|",
        "| `NameError` | 用到沒定義的變數 | 先檢查拼字 |",
        "| `SyntaxError` | 語法錯（少括號、引號） | 看錯誤指標的位置 |",
        "| `IndentationError` | 縮排錯 | Python 用 4 空格 |",
        "| `TypeError` | 型別不對（字串+數字） | 轉型 str() / int() |",
        "| `IndexError` | list 索引超出範圍 | 檢查長度 `len(list)` |",
        "| `KeyError` | dict 沒這個 key | 用 `dict.get(key, default)` |",
        "| `ZeroDivisionError` | 除以 0 | 加 if 判斷 |",
        "| `FileNotFoundError` | 檔案不存在 | 檢查路徑 |",
        "",
        "## 📚 延伸閱讀",
        "- [How to ask questions](https://stackoverflow.com/help/how-to-ask)",
        "- [Python 官方錯誤說明](https://docs.python.org/3/tutorial/errors.html)",
        "- [Rubber duck debugging](https://en.wikipedia.org/wiki/Rubber_duck_debugging)",
        "",
        "---",
        "",
        "準備好了嗎？ → [第 1 章 基礎語法](../chapter01_basics/01-variables-types.md) 🚀",
    ]),

    ("章末小測驗", "第 0 章 小測驗", "10 分鐘", "📝 自我檢測", "複習 + 確認學習成效", [
        "## 📝 選擇題（10 題）",
        "",
        "??? question \"Q1. 為什麼要學 Python？\"",
        "    - A) Python 是最快的程式語言",
        "    - B) Python 語法簡潔、套件多、社群大",
        "    - C) 只能用 Python 做網站",
        "    - D) 只能在 macOS 用",
        "",
        "    ??? success \"答案\"",
        "        ✅ **B** — Python 的優勢在語法簡潔、套件多、社群大。",
        "",
        "??? question \"Q2. Python 官方網站是哪個？\"",
        "    - A) python.com",
        "    - B) python.org",
        "    - C) python.dev",
        "    - D) python.net",
        "",
        "    ??? success \"答案\"",
        "        ✅ **B** — [https://www.python.org](https://www.python.org)",
        "",
        "??? question \"Q3. macOS 安裝 Python 最推的方式是？\"",
        "    - A) Microsoft Store",
        "    - B) 下載 .pkg 從官網",
        "    - C) Homebrew",
        "    - D) 不用裝，macOS 內建就有",
        "",
        "    ??? success \"答案\"",
        "        ✅ **C** — Homebrew 是 macOS 開發者最常用方式。",
        "",
        "??? question \"Q4. VS Code 必裝的 Python 擴充 ID 是？\"",
        "    - A) python-vscode",
        "    - B) ms-python.python",
        "    - C) python-extension",
        "    - D) py-vscode",
        "",
        "    ??? success \"答案\"",
        "        ✅ **B** — `ms-python.python`",
        "",
        "??? question \"Q5. `print('Hi')` 的輸出是？\"",
        "    - A) Hi（無引號）",
        "    - B) 'Hi'",
        "    - C) \\\"Hi\\\"",
        "    - D) error",
        "",
        "    ??? success \"答案\"",
        "        ✅ **A** — 螢幕只印 Hi 兩個字元",
        "",
        "??? question \"Q6. `input()` 拿到的值是什麼型別？\"",
        "    - A) 數字",
        "    - B) 浮點數",
        "    - C) 字串",
        "    - D) 布林",
        "",
        "    ??? success \"答案\"",
        "        ✅ **C** — `input()` 永遠回傳字串，要數字要 `int(input())`",
        "",
        "??? question \"Q7. Python 錯誤訊息的最後一行是什麼？\"",
        "    - A) 發生錯誤的行號",
        "    - B) 錯誤類型",
        "    - C) 函式名",
        "    - D) 變數名",
        "",
        "    ??? success \"答案\"",
        "        ✅ **B** — 最後一行是錯誤類型（如 NameError、TypeError）",
        "",
        "??? question \"Q8. 哪個不是 Python 編輯器？\"",
        "    - A) VS Code",
        "    - B) PyCharm",
        "    - C) Jupyter Notebook",
        "    - D) Microsoft Word",
        "",
        "    ??? success \"答案\"",
        "        ✅ **D** — Word 是文書處理軟體，不能寫程式",
        "",
        "??? question \"Q9. 問問題的 MCVE 是什麼縮寫？\"",
        "    - A) Most Common Version Editor",
        "    - B) Minimal Complete Verifiable Example",
        "    - C) My Code Very Easy",
        "    - D) Module Class Variable Error",
        "",
        "    ??? success \"答案\"",
        "        ✅ **B** — Minimal Complete Verifiable Example（最小可重現範例）",
        "",
        "??? question \"Q10. 哪個 Python 版本推薦使用？\"",
        "    - A) Python 2.7",
        "    - B) Python 3.6",
        "    - C) Python 3.11+",
        "    - D) Python 4.0",
        "",
        "    ??? success \"答案\"",
        "        ✅ **C** — Python 3.11+ 推薦，2.7 已停止維護",
        "",
        "## 💻 實作題（5 題）",
        "完整答案在 [附錄 E](../appendix/E-answers.md)，**先自己寫再看**。",
        "",
        "### 練習 1：自我介紹",
        "寫一個程式問使用者 3 個問題（名字、年齡、興趣），然後印出自我介紹。",
        "",
        "### 練習 2：簡單計算機",
        "寫一個程式問使用者兩個數字，印出他們的和、差、積、商。",
        "",
        "### 練習 3：溫度轉換",
        "寫一個程式把攝氏轉華氏：`F = C * 9/5 + 32`",
        "",
        "### 練習 4：BMI 計算",
        "輸入體重 (kg) 跟身高 (cm)，輸出 BMI。 `BMI = 體重 / (身高/100)²`",
        "",
        "### 練習 5：Debug 練習",
        "這段程式有 3 個錯，請找出來並修正：",
        "```python",
        "name = input(你叫什麼名字？)",
        "age = int(input('你幾歲？ ')",
        "print(f'你是 {name}, {Age} 歲')",
        "```",
        "",
        "## 🎯 過關標準",
        "- 選擇題 ≥ 8 題對（80%）",
        "- 實作題至少完成 3 題",
        "",
        "**達標了？** → [第 1 章 基礎語法](../chapter01_basics/01-variables-types.md) 🚀",
        "**沒達標？** → 回去重看 [0.2](02-install.md) / [0.3](03-vscode.md) / [0.4](04-hello.md)",
    ]),
]

# 寫入
for title_key, h1, time, audience, level, content_lines in CHAPTER_0:
    chapter_tag = "第 0 章 · 環境準備"
    header = lesson_header(chapter_tag, h1, time, audience, level)
    out = header + "\n".join(content_lines)
    fname = title_key.split(" ")[0].replace(".", "")
    if "測驗" in title_key:
        fname = "quiz"
    path = ROOT / "chapter0X_setup" / f"{fname}.md"
    with open(path, "w", encoding="utf-8") as f:
        f.write(out)
    print(f"✅ {path.name} ({len(out)} chars)")

print(f"\n完成第 0 章剩 {len(CHAPTER_0)} 個檔案")
